version: '{build}'

branches:
  only:
  - master
clone_depth: 1

image: Visual Studio 2019
environment:
  py: python3
  vlc: without-vlc
  matrix:
  - arch: x86_64
    mingw: mingw64
  - arch: i686
    mingw: mingw32

build_script:
- cmd: C:\msys64\msys2_shell.cmd -%mingw% -defterm -here -no-start -c "pacman -Syu --noprogressbar --noconfirm"
- cmd: C:\msys64\msys2_shell.cmd -%mingw% -defterm -here -no-start scripts\build_msi_mingw.sh

test_script:
- cmd: call scripts\test_msi.bat
- cmd: call refreshenv
- cmd: pympress --help

artifacts:
- path: dist/*


deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  description: Automated upload of windows binaries
  auth_token:
    secure: 99OQhliIMiV/Z1/kuZQ3TxR55Qb7Y2zaD7ZV6/JUaUGDbAxHzep97/yBLfM21Jzw
  draft: true
  force_update: false
  on:
    appveyor_repo_tag: true
