version: '{build}'

branches:
  only:
  - master
skip_non_tags: true
clone_depth: 1

image: Visual Studio 2019
environment:
  py: python3
  vlc: without-vlc
  matrix:
  - arch: x86_64
    mingw: mingw64
  - arch: i686
    mingw: mingw32

init:
- cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
- cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"

build_script:
- cmd: C:\msys64\msys2_shell.cmd -%mingw% -defterm -here -no-start scripts\build_msi_mingw.sh

test_script:
- cmd: call scripts\test_msi.bat
- cmd: call refreshenv
- cmd: pympress --help

artifacts:
- path: dist/*


deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  description: Automated upload of windows binaries
  auth_token:
    secure: P934PvEuB4UQKvsc/QXa0VVKu/4msuf5IuW3n+tpGLG68TpE9VqL4PsXMzHqfT1h
  draft: true
  force_update: false
  on:
    appveyor_repo_tag: true
