#!/bin/sh

# should not be in local dir
TEMPFILE=/tmp/pympress-gh-pages.tar
DOC="$(dirname $0)"
TOP=$(cd "$DOC" && git rev-parse --show-toplevel)

pushd "$TOP"

make -C "$DOC" clean && make -C "$DOC" $TEMPFILE && make -C "$DOC" clean &&
git checkout gh-pages && git clean -fdx && \
rm -fr *.html *.js *.inv _sources/* _static/* && \
tar xf $TEMPFILE && touch .nojekyll

rm $TEMPFILE
git status

popd

