name: Run macOS brew install and test

on: [push, pull_request]

jobs:
  macos:
    name: Install and run test on mac
    runs-on: macos-latest
    steps:
    - name: Install latest
      run: |
        brew install Cimbali/core/pympress --only-dependencies
        brew install Cimbali/core/pympress --build-from-source --HEAD

    - name: Test
      run: |
        brew test pympress
