name: Run macOS brew install and test

on: push

jobs:
  macos:
    name: Install and run test on mac
    runs-on: macos-latest
    steps:
    - name: Install latest
      run: |
        brew install pympress --only-dependencies
        brew install pympress --build-from-source --HEAD

    - name: Test
      run: |
        brew test pympress
