name: Upload python package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine babel
    - name: Build catalogs
      env:
        poeditor_api_token: ${{ secrets.POEDITOR_API_TOKEN }}
      run: |
        ./scripts/poedit.sh download
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py compile_catalog
        python setup.py sdist bdist_wheel
        twine upload dist/*

  brew:
    name: Request new pypi package be pulled into Homebrew
    needs: pypi
    runs-on: macos-latest

    steps:
    - name: Install dependencies
      run: |
        brew update
        brew install jq

    - name: Wait a reasonable amount of time for pypi to update its info
      run: sleep 60  # be patient with pypi

    - name: Configure brew repo
      run: |
        # Credentials and remotes
        git="git -C `brew --repo`/Library/Taps/homebrew/homebrew-core/"
        $git config user.name Cimbali
        $git config user.email me@cimba.li
        $git config credential.helper store
        echo -e "protocol=https\nhost=github.com\nusername=Cimbali\npassword=$PASSWORD" | $git credential-store store
        $git remote add gh "https://github.com/Cimbali/homebrew-core.git"
        # Attempt a rebase of changes in our repo copy
        $git fetch gh
        $git rebase origin/master gh/master && git branch -f master HEAD || git rebase --abort
        # Now use master and update remote
        $git checkout master
        $git push gh -f master:master
      env:
        PASSWORD: ${{ secrets.GITHUB_HOMEBREW_TOKEN }}

    - name: Make a brew PR from pypi’s metadata
      run: |
        tag=${GITHUB_REF#refs/tags/}
        jq_script=`printf '.releases."%s"[]? | select(.python_version == "source") | @text "--url=\(.url) --sha256=\(.digests.sha256)"' ${tag#v}`
        brew bump-formula-pr --strict --no-browse `curl -s https://pypi.org/pypi/pympress/json | jq -r "$jq_script"` pympress
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_HOMEBREW_TOKEN }}
        HUB_REMOTE: https://github.com/Cimbali/homebrew-core/
